replicaCount: 2

image:
  repository: pavant049/nodejs
  tag: v1.0

service:
  type: NodePort
  port: 80
  targetPort: 3000

containerPort: 3000

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"
